:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]
:navigation:
:menu:
:status:
:title-slide-background-image: gr8eu-logo-2019.svg
:title-slide-background-size: auto 75%
:title-slide-background-position: center top
:title-slide-transition: zoom
:title-slide-transition-speed: fast
:icons: font

= : Application Security Options

+++<h2>+++
SmartThings Case Study
+++</h2>+++

[.notes]
--
Abstract

When building a modern IoT platform you will have security concerns that span from hardware all the way out to consumers phones. We will go through a deep dive of many security concepts and talk about pros/cons of each option while discussing how we have scaled our solutions.

The SmartThings cloud platform is a microservice architecture built out across many deployment methodologies in the cloud and we allow deep integrations from external developers. 

Some of the security tech we will cover while also talking about how to scale these practices: 
* HTTP Signatures
* JWT/JWS/JWE
* OAuth
** prefix routing
** metrics on number of uses for a tokens life cycle 

After we get through a foundation of these security approaches we will work through these scenarios with real world examples from my experience at SmartThings

* OAuth Provider
* OAuth Consumer

By the end I you will have a good understanding of when you could make use of these different security methods.
--

== [.line-through]#Application Security Options#
+++<h2>+++
Authorization and Authentication Options
+++</h2>+++

== Agenda

* Intro
* Terminology 
* OAuth 2
* JWT Family
* HTTP Signatures
* SmartThings Uses
* Scaling Auth


include::shared/whoami.adoc[]

include::shared/about-st.adoc[]

include::gr8eu-2019-security/term.adoc[]

include::gr8eu-2019-security/oauth.adoc[]

include::gr8eu-2019-security/jwt.adoc[]

include::gr8eu-2019-security/http-sig.adoc[]

include::gr8eu-2019-security/st-use.adoc[]

include::gr8eu-2019-security/scale.adoc[]

include::shared/end.adoc[]